print("Hello AI engineering")
print("Day 1 completed")
print("I am building my first LLM RAG application")
name = input("What is your name? ")
print(f"Nice to meet you, {name}!")
print("Welcome to AI engineering!")
age = input("what is your age? ")
print(f"Interesting, {age} is a great age to start your AI engineering journey!")